services:
  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.17.1
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable
    command:
      - "--collector.wal"
      - "--collector.replication"
      - "--collector.stat_wal_receiver"
      - "--collector.xlog_location"
      # (option) Log Level : "--log.level=info"
    ports:
      - "9187:9187"
